production:
  primary: &primary_production
    <<: *default
    database: stock_trading_app_production
    username: <%= ENV['POSTGRES_USERNAME'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>

  cache:
    <<: *primary_production
    database: stock_trading_app_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: stock_trading_app_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: stock_trading_app_production_cable
    migrations_paths: db/cable_migrate